"use client";
import './globals.css'
import {
  createDOMRenderer,
  renderToStyleElements,
} from "@fluentui/react-components";
import React from "react";
import dynamic from "next/dynamic";
import { Metadata } from 'next';
const AppProvider = dynamic(
  () => import("./AppProvider").then((mod) => mod.AppProvider),
  { ssr: false }
);
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function Root({ children }: React.PropsWithChildren) {
  const renderer = React.useMemo(() => createDOMRenderer(), []);
  const styles = React.useMemo(
    () => renderToStyleElements(renderer),
    [renderer]
  );

  return (
    <html>
      <head>{styles}</head>
      <body>
        <div className='flex'>
        <div className='h-[100vh] w-[32px] bg-black'>abcdefg</div>
        <AppProvider renderer={renderer}>{children}</AppProvider>
        </div>
      </body>
    </html>
  );
}
